server:
  port : 9999
#spring:
#  security:
#    user:
#      name: sarath
#      password: sarath123
#      roles: ADMIN,USER
#
#security:
#  oauth2:
#    client:
#      client-id: mobile
#      client-secret: pin
#      access-token-validity-seconds: 3600
#      authorized-grant-types: refresh_token,authorization_code,password,client_credentials
#      scope: READ,WRITE
#    authorization:security:
#      oauth2:
#        client:
#          client-id: mobile
#          client-secret: pin
#          access-token-validity-seconds: 3600
#          authorized-grant-types: refresh_token,authorization_code,password,client_credentials
#          scope: READ,WRITE
#        authorization:
#      check-token-access: permitAll
# : com.mysql.cj.jdbc.Driver

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authDB?createDatabaseIfNotExist=true
    username: sarath
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace
debug: true